// <auto-generated />
using System;
using DataForInventoryReconciliation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataForInventoryReconciliation.Migrations
{
    [DbContext(typeof(S5WebApiContext))]
    [Migration("20200224122926_init2")]
    partial class init2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataForInventoryReconciliation.Models.APBill", b =>
                {
                    b.Property<int>("APBillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BillCommentLinesBillCommentLineId")
                        .HasColumnType("int");

                    b.Property<string>("EnterDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("EnterTime")
                        .HasColumnType("real");

                    b.Property<int?>("HeaderInfoBillHeaderId")
                        .HasColumnType("int");

                    b.Property<int?>("PayeeBillPayeeId")
                        .HasColumnType("int");

                    b.Property<int?>("SupplierBillSupplierId")
                        .HasColumnType("int");

                    b.Property<int>("Unique")
                        .HasColumnType("int");

                    b.HasKey("APBillId");

                    b.HasIndex("BillCommentLinesBillCommentLineId");

                    b.HasIndex("HeaderInfoBillHeaderId");

                    b.HasIndex("PayeeBillPayeeId");

                    b.HasIndex("SupplierBillSupplierId");

                    b.ToTable("APBills");
                });

            modelBuilder.Entity("DataForInventoryReconciliation.Models.BillCommentLine", b =>
                {
                    b.Property<int>("BillCommentLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommentLineData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CommentLineIndex")
                        .HasColumnType("int");

                    b.HasKey("BillCommentLineId");

                    b.ToTable("BillCommentLines");
                });

            modelBuilder.Entity("DataForInventoryReconciliation.Models.BillHeader", b =>
                {
                    b.Property<int>("BillHeaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DueDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Foreign")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pay")
                        .HasColumnType("int");

                    b.Property<int>("Supplier")
                        .HasColumnType("int");

                    b.Property<float>("Total")
                        .HasColumnType("real");

                    b.HasKey("BillHeaderId");

                    b.ToTable("BillHeaders");
                });

            modelBuilder.Entity("DataForInventoryReconciliation.Models.BillLine", b =>
                {
                    b.Property<int>("BillLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<int?>("BillUnique")
                        .HasColumnType("int");

                    b.Property<int>("CurrencyCode")
                        .HasColumnType("int");

                    b.Property<string>("CurrencyDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DbCd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LedgerAccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LedgerAccountName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Supplier")
                        .HasColumnType("int");

                    b.Property<int>("WholeCurrencyCode")
                        .HasColumnType("int");

                    b.HasKey("BillLineId");

                    b.ToTable("BillLines");
                });

            modelBuilder.Entity("DataForInventoryReconciliation.Models.BillPayee", b =>
                {
                    b.Property<int>("BillPayeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContextUnique")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Location")
                        .HasColumnType("int");

                    b.Property<string>("Phone_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Unique")
                        .HasColumnType("int");

                    b.HasKey("BillPayeeId");

                    b.ToTable("Payees");
                });

            modelBuilder.Entity("DataForInventoryReconciliation.Models.BillSupplier", b =>
                {
                    b.Property<int>("BillSupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContextUnique")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Location")
                        .HasColumnType("int");

                    b.Property<string>("Phone_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Unique")
                        .HasColumnType("int");

                    b.HasKey("BillSupplierId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("DataForInventoryReconciliation.Models.APBill", b =>
                {
                    b.HasOne("DataForInventoryReconciliation.Models.BillCommentLine", "BillCommentLines")
                        .WithMany()
                        .HasForeignKey("BillCommentLinesBillCommentLineId");

                    b.HasOne("DataForInventoryReconciliation.Models.BillHeader", "HeaderInfo")
                        .WithMany()
                        .HasForeignKey("HeaderInfoBillHeaderId");

                    b.HasOne("DataForInventoryReconciliation.Models.BillPayee", "Payee")
                        .WithMany()
                        .HasForeignKey("PayeeBillPayeeId");

                    b.HasOne("DataForInventoryReconciliation.Models.BillSupplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierBillSupplierId");
                });
#pragma warning restore 612, 618
        }
    }
}
